### PR TITLE
Updated python scripts to support python 3

### PR DESCRIPTION
**Pull request by anoek**
Both scripts remain backwards compatable with Python 2.7

This fixes issue FontCustom/fontcustom/#272

### CODE REVIEW

**Comment by dkniffin** [comment]
Can we get this merged?

**Comment by Lukas-W** [comment]
:+1:

**Comment by LukeSwart** [comment]
I am just confirming that this fix is working. I am on Arch, which has python3 as the default, and I was running into issue #272. After building and installing this gem locally from anoek's fork, the issue is resolved.

It would probably be very helpful to others if this PR was merged.

**Comment by tisOO** [comment]
:+1: It helps me on ArchLinux. Thank you!

**Pull request merged**
