### PR TITLE
Support listen 3.x

### PR DESCRIPTION
**Pull request by twalpole**
Support listen 3.x and update travis config to match

### CODE REVIEW

**Comment by tdreyno** [comment]
:+1:

**Comment by saneshark** [comment]
:+1: 

please update the dependency as this is affecting my ability use guard and terminal notifier with latest OSX.

**Comment by saneshark** [comment]
@kaizau is this something we could merge and bump versions on?

**Comment by bradgessler** [comment]
:+1: running into this issue while trying to upgrade middleman to 4.x.

**Comment by tibastral** [comment]
Hey, could you merge this PR ? It's pretty useful !

Thank you very much !

**Comment by shehi** [comment]
This PR is very essential now, as our CI/CD routine became broken due to #150 . Please merge asap.

**Comment by pjg** [comment]
Any chance of maintainer to release a new version with this patch? The `listen < 3.0` constain is blocking a lot of gem upgrades (guard, celluloid).

**Comment by JakeBeresford** [comment]
This PR is essential to our projects use of fontcustom, please release a new version with this change ASAP!

**Comment by GesJeremie** [comment]
Time to merge guys!

**Comment by meowsus** [comment]
It would be amazingly helpful if this PR was merged @kaizau

**Comment by kaizau** [comment]
Apologies for the long hiatus, everyone. This little gem deserves more love and attention than I'm able to give.

Big thanks to @JakeBeresford for reaching out and offering to help. I've added him as a maintainer, and an update should be coming shortly.

**Comment by meowsus** [comment]
Big ups @jakeberesford!

**Comment by AxelTheGerman** [comment]
Thanks @JakeBeresford for stepping up, and thanks @kaizau for all the work you have put in!

**Pull request merged**
