### PR TITLE
Works with Windows.

### PR DESCRIPTION
**Pull request by jdell64**
I created a few changes here:
1. base.rb checks to see if you are on a Windows platform. It will run 'which' instead of 'where' if so.
2. generate.py will check to see if the os.name is 'nt'. If it is, it will open 'sfnt2woff.exe' instead of sfnt2woff. Note: mignw will not come back as 'nt' this should not cause any issues.
3. sfnt2woff.exe is added to scripts folder.

### CODE REVIEW

**Comment by skolmer** [comment]
@jdell64 Thanks! @kaizau Please accept this pull request to add windows support to FontCustom

**Comment by jdell64** [comment]
I have updated it. Not sure how to get this code up here...

**Comment by TWiStErRob** [comment]
#17

**Comment by jdell64** [comment]
I haven't heard anything back... did my new changes make it in?

**Comment by miguelcobain** [comment]
@jdell64 Can you help me installing this branch?

Now I just need to `gem install fontcustom`, but since these changes stil aren't on master, I need to install your branch.

**Comment by jdell64** [comment]
Sure... You can just clone my repo wherever you installed your gems to.

On Friday, September 25, 2015, Miguel Andrade <notifications@github.com>
wrote:

> @jdell64 <https://github.com/jdell64> Can you help me installing this
> branch?
>
> Now I just need to gem install fontcustom, but since these changes stil
> aren't on master, I need to install your branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FontCustom/fontcustom/pull/289#issuecomment-143189944>
> .
>


-- 

--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by miguelcobain** [comment]
@jdell64 Thanks a lot! I ended up installing the normal fontcustom and replacing the directoy.
Hope this gets merged soon.

**Comment by jdell64** [comment]
Oh good.


--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by guidobouman** [comment]
@kaizau @endtwist Time to merge this?

**Comment by rasmusmilz** [comment]
Happy to see this taken up again, as I'm just about to find a library that supports windows for SVG to font generation. 
However i get this error when i try to run "fontcustom compile"
`C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:45:in ``': No such file or directory - which woff2_compress (Errno::ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:45:in `check_woff2'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/lib/fontcustom/base.rb:9:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/lib/fontcustom/cli.rb:83:in `compile'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fontcustom-2.0.0/bin/fontcustom:5:in `<top (required)>'
        from C:/Ruby22-x64/bin/fontcustom:23:in `load'
        from C:/Ruby22-x64/bin/fontcustom:23:in `<main>'`

**Comment by jdell64** [comment]
Not sure why are you aren't getting the more helpful error message, but you are failing at this block of code:
`def check_woff2
      woff2 = `which woff2_compress`
      if woff2 == "" || woff2 == "woff2_compress not found"
        fail Fontcustom::Error, "Please install woff2 first. Visit <https://github.com/google/woff2> for instructions."
      end
    end`

**Comment by rasmusmilz** [comment]
@jdell64 No i have not installed woff2. 
Since you now added sfnt2woff to the scripts which should be a substitute for that, as far as I understand. 

I have been looking a bit into the code and can see they (base.rb file) are very different in your branch(https://github.com/jdell64/fontcustom) and the master branch here. The code snippet you just copied is not present in your branch which makes sense since it should not check for something that will never exist on windows i guess?

**Comment by jdell64** [comment]
Hey, your right... that file is different... I have no idea what is going on here...

**Comment by rasmusmilz** [comment]
Yes, glad it's not just me who is confused!

But anyway thank you for the windows support. 
I have been taking over a project which has been using fontcustom (on mac) which is now moved to a 100% windows env. and i haven't been able to find ANY other good svg to font libraries out there. 
But yours seems to work good!

I hope at some point it will be merged correctly into the Master branch here.

**Comment by jdell64** [comment]
Looks like they added woff2 support... I think there should be a function to determine which `which` command (which or where) to run... let me make a PR for this.

**Comment by rasmusmilz** [comment]
@jdell64 I also found that your code is not generating the EOT file - even though it says its generated in the console. There was an issue with this on the FontCustom somewhere, but it's closed.

**Pull request merged**
